apiVersion: kannika.io/v1alpha
kind: Backup
metadata:
  name: redpanda
  namespace: kannika-data
spec:
  source: redpanda
  sink: siege
  compression:
    algorithm: zstd
  streams:
    - topic: kings-landing
    - topic: winterfell
    - topic: the-wall
    - topic: iron-islands
    - topic: dragonstone
    - topic: the-citadel
